# Generated by Django 5.0.6 on 2024-06-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_author_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                default=10, on_delete=django.db.models.deletion.CASCADE, to="app.author"
            ),
        ),
    ]
