# Generated by Django 5.0.6 on 2024-06-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_book_added_by_book_isbn_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="parent_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.review",
            ),
        ),
    ]
