# Generated by Django 5.0.6 on 2024-06-16 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
