# Generated by Django 5.0.6 on 2024-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_book_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="short_description",
            field=models.TextField(),
        ),
    ]
