# Generated by Django 5.0.6 on 2024-06-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_author_birth_date_alter_author_short_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="short_bio",
            field=models.TextField(default="No bio available", null=True),
        ),
    ]
