# Generated by Django 5.0.6 on 2024-07-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="app.genre"),
        ),
    ]
