# Generated by Django 5.0.6 on 2024-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_book_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(default="slug1", unique=True),
            preserve_default=False,
        ),
    ]
