# Generated by Django 5.0.6 on 2024-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_genre_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(),
        ),
    ]
