# Generated by Django 5.0.6 on 2024-07-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_genre_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="slug",
        ),
    ]
