# Generated by Django 5.0.6 on 2024-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_remove_genre_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(default="test-slug", unique=True),
            preserve_default=False,
        ),
    ]
