# Generated by Django 5.0.6 on 2024-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_genre_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
    ]
