# Generated by Django 5.0.6 on 2024-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="../static/profile_picture/default.png",
                upload_to="profile_picture",
            ),
        ),
    ]
