# Generated by Django 5.0.6 on 2024-08-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
